config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  get 'welcome/index'

  #root :to => "welcome#index"
  root to: "home#index"

  resources :images

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
	mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_devise_params, if: :devise_controller?

	def configure_devise_params
		devise_parameter_sanitizer.permit(:sign_up) do |user|
		user.permit(:name, :email, :password, :password_confirmation)
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

	before_action :set_image, only: [:show, :edit, :update, :destroy]
=begin
	Damos permisos para la captura de los parametros de nuestro formulario
=end
	
	## si se declara privado todo desde aquí, hasta que no se haga una declaración diferente de visibilidad (public, protected) todos los métodos serán accesibles solo dentro del controlador
	private
	
    def images_params
		params.require(:image).permit :description, :picture
	end

    def set_image
		@image = Image.find params[:id]
	end

	##SE CAMBIA LA VISIBILIDAD DE AQUÍ EN ADELANTE A PUBLICA
    public

=begin
	Creaciòn de una nueva instancia de la imagen
=end
	def new 
		@image = Image.new
	end


	def create 
		#render plain: params[:image].inspect
        @image = Image.new images_params
        @image.save

        redirect_to @image  #redirecciona a una nueva vista
    end

=begin
	Creamos nuestro metodo show para visualizar nuestro objeto imagen
=end
    def show
    	
    end

=begin
	Creamos nuestro metodo index en el controlador para visualizar todos los objetos creados. 
=end
    def index
        @images = Image.all            # variable de tipo array @images
   	end

	def edit
		
	end

	def update
		
		@image.update images_params
		redirect_to @image
	end

	def destroy
		
		@image.destroy
		redirect_to images_path
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<h1>ImageGram</h1>
	<% if user_signed_in? %>
		<h3>Bienvenido! <%= current_user.name %> </h3>
	<% else %>
		<p> por favor inicia sesión para ver imagenes </p>
	<% end %>

app/views/images/_form.html.erb
<div class="form-group">
	<%= form_for @image, :html => {:multipart => true} do |f| %>
	<%= f.label :description %> <br>
	<%= f.text_field :description, class: 'form-control' %>
	<br>
	<%= f.label 'Cargar Imagen ' %> <br>
	<%= f.file_field :picture, class: 'form-control-file' %>
	<br>
	<%= f.submit 'Enviar', :class => 'btn btn-primary' %>
	<% end %>
</div>

app/views/images/_image.html.erb
<div class="col-sm-4">
	<figure class="figure">
	<%= image_tag image.picture.thumb.url, class: 'figure-img img-fluid rounded' %>
	<figcaption class="figure-caption">
		<%= image.description %>
		<%= link_to 'Editar', edit_image_path(image) %>
		<%= link_to 'Eliminar', image, method: :delete, data:{
		confirm: 'Esta seguro que desea eliminar esta imagen.'
		} %>
	</figcaption>
	</figure>
</div>

app/views/images/edit.html.erb
<h1> Editar imágen </h1>
<br>
<%= render 'form' %>

app/views/images/index.html.erb
<h1> Imágenes cargadas </h1>
<br>
<div class="row">
	<%= render @images %>
</div>

app/views/images/new.html.erb
<h1> Insertar Imagen </h1>

<%= render 'form' %>

app/views/images/show.html.erb
<%= @image.description %>
<%= image_tag @image.picture.thumb.url, class: 'figure-img img-fluid rounded' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <ul class=”nav justify-content-end”>
      <%- if user_signed_in? %>
        <li class=”nav-item”>
          <%= link_to 'Salir', destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li class=”nav-item”>
          <%= link_to 'Iniciar Sesión', new_user_session_path %>
        </li>
        <li class=”nav-item”>
          <%= link_to 'Registrarse', new_user_registration_path %>
        </li>
      <% end %>
  </ul>
	<div class="container">
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
     <%= yield %>
	</div>

  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<button class="btn-primary" onclick="showHolaMundo()"> Ingresar</button>
<a id="holaMundo" class="col-lg-2" hidden="true">HOLA MUNDO</a>

<script type="text/javascript">
	function showHolaMundo() {
		document.getElementById("holaMundo").hidden = false;
	}
</script>